# APP VARS
APP_NAME = "Habitica Auto Potion"
WARN_THRESHOLD = 0.4  # or an integer for a flat value

# API VARS
HABITICA_USER_ID = "YOUR_HABITICA_ID"
HABITICA_API_TOKEN = "YOUR_HABITICA_API_TOKEN"
PUSHBULLET_API_KEY = "YOUR_PUSHBULLET_API_KEY"

